apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: farmacia-ingress
  namespace: farmacia-compare
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - farmaciacompare.cl
        - api.farmaciacompare.cl
        - dashboard.farmaciacompare.cl
      secretName: farmacia-tls
  rules:
    - host: farmaciacompare.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: api.farmaciacompare.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000
    - host: dashboard.farmaciacompare.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 3001
