apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: farmacia-compare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: REGISTRY/farmacia-scraper:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farmacia-secrets
                  key: database-url
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: farmacia-secrets
                  key: elasticsearch-url
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
